# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flags' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flags
	pod 'SwiftGen', '~> 6.0'

  target 'FlagsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlagsUITests' do
    # Pods for testing
  end

end
